<?xml version="1.0"?>
<package format="3">
  <name>sam3_trt_ros</name>
  <version>0.1.0</version>
  <description>ROS 2 integration for InstinctSAM and SAM2 TensorRT hybrid tracking.</description>
  <maintainer email="maintainer@example.com">Efficient SAM3 TensorRT maintainers</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>sam2_trt_msgs</exec_depend>
  <exec_depend>sam2_trt_ros</exec_depend>
  <exec_depend>sam3_trt_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
